name: Lint
on: 
  push: 
    branches: [dev]
  pull_request: 
    branches: [dev]
jobs: 
  lint: 
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: pnpm ci
      - name: Lint
        run: pnpm run lint